# Generated by Django 6.0.4 on 2026-05-04 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_remove_merchant_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
    ]
